#!/usr/bin/env bash

set -eo pipefail

COMPOSE_FILE=docker-compose.yml
[[ -f docker-compose-production.yml ]] && COMPOSE_FILE=docker-compose-production.yml

docker-compose -f "$COMPOSE_FILE" build
docker-compose -f "$COMPOSE_FILE" up -d
