#!/usr/bin/env bash

set -eo pipefail
FROM=$(git rev-parse HEAD)
TO="$1"

echo >&2 updating from "$FROM" to "$1"...

git reset --hard
trap 'git reset --hard' EXIT

git update-index -q --refresh && git read-tree -u -m HEAD "$1" || {
    status=$?
    echo >&2 read-tree failed
    exit $status
}

docker-compose up -d --build --remove-orphans
trap - EXIT
git tag "$1" -f latest
